services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: my_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  migrate:
    build:
      context: ./migrate
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/mydb?sslmode=disable
    command: >
      sh -c "
        goose -dir ./migrations postgres postgres://postgres:postgres@db:5432/mydb?sslmode=disable up
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  notification_app:
    build: ./notification
    container_name: notification_service
    ports:
      - "8083:8080"
    environment:
      RABBITMQ_URL: amqp://user:pass@rabbitmq:5672/my_vhost
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
      schedule_app:
        condition: service_started
      user_app:
        condition: service_started
      booking_app:
        condition: service_started
    networks:
      - backend

  user_app:
    build: ./user
    container_name: user_service
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/mydb?sslmode=disable
      RABBITMQ_URL: amqp://user:pass@rabbitmq:5672/my_vhost
      PORT: 8080
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend
 
  booking_app:
    build: ./booking
    container_name: booking_service
    ports:
      - "8082:8080"
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/mydb?sslmode=disable
      RABBITMQ_URL: amqp://user:pass@rabbitmq:5672/my_vhost
      PORT: 8080
      SCHEDULE_HOST: schedule_service
      SCHEDULE_PORT: 8080
      USER_HOST: user_service
      USER_PORT: 8080
    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      user_app:
        condition: service_started
      schedule_app:
        condition: service_started
    restart: unless-stopped
    networks:
      - backend

  schedule_app:
    build: ./schedule
    container_name: schedule_service
    ports:
      - "8081:8080"
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/mydb?sslmode=disable
      PORT: 8080
      USER_HOST: user_service
      USER_PORT: 8080
    depends_on:
      migrate:
        condition: service_completed_successfully
      user_app:
        condition: service_started
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  backend:
    driver: bridge
