syntax = "proto3";

package rating;

option go_package = "/bb";

service RatingService {
     rpc CreateReview (CreateReviewRequest) returns (ReviewResponse);
     rpc GetReview (ReviewIdRequest) returns (ReviewResponse);
     rpc DeleteReview (ReviewIdRequest) returns (Empty);
     rpc ListReviewsForUser (UserIdRequest) returns (ReviewListResponse);
}

message Review {
     string id = 1;
     string from_id = 2;
     string to_id = 3;
     string comment = 4;
     int32 rating = 5;
}

message CreateReviewRequest {
     string from_id = 1;
     string to_id = 2;
     string comment = 3;
     int32 rating = 4;
}

message ReviewIdRequest {
     string id = 1;
}

message ReviewResponse {
     Review review = 1;
}

message ReviewListResponse {
     repeated Review reviews = 1;
}

message UserIdRequest {
     string id = 1;
}

message Empty {}
