syntax = "proto3";

package user;

option go_package = "/bb";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service UserService {
	rpc CreateUser (CreateUserRequest) returns (UserResponse);
	rpc GetUser (UserIdRequest) returns (UserResponse);
	rpc UpdateUser (UpdateUserRequest) returns (UserResponse);
	rpc DeleteUser (UserIdRequest) returns (google.protobuf.Empty);
	rpc ListUsers (google.protobuf.Empty) returns (UserListResponse);

	rpc Login (LoginRequest) returns (AuthResponse);
	rpc Logout (UserIdRequest) returns (google.protobuf.Empty);
}

message User {
	string id = 1;
	string name = 2;
	string bio = 3;
	string username = 4;
	string email = 5;

	string specialization = 7;
	string role = 8;
	bool is_active = 9;
	bool email_verified = 10;

	google.protobuf.Timestamp last_login_at = 11;
	string last_ip = 12;

	google.protobuf.Timestamp deleted_at = 13;
	google.protobuf.Timestamp created_at = 14;
	google.protobuf.Timestamp updated_at = 15;
}

message CreateUserRequest {
	string name = 1;
	string bio = 2;
	string username = 3;
	string email = 4;
	string password = 5;
	string specialization = 6;
	string role = 7;
}

message UpdateUserRequest {
	string id = 1;
	string name = 2;
	string bio = 3;
	string email = 4;
	string specialization = 5;
	string role = 6;
	bool is_active = 7;
	bool email_verified = 8;
}

message UserIdRequest {
	string id = 1;
}

message LoginRequest {
	string username = 1;
	string password = 2;
}

message AuthResponse {
	string token = 1;
}

message UserResponse {
	User user = 1;
}

message UserListResponse {
	repeated User users = 1;
}
